---
# file: roles/splunk/tasks/main.yml
- name: splunk check
  command: rpm -q splunk
  register: is_splunk_installed
  failed_when: is_splunk_installed.rc not in [0,1]
  changed_when: is_splunk_installed.rc != 0

- name: splunk rpm copy
  copy: src={{ splunk_rpm }} dest=/tmp
  when: is_splunk_installed.rc == 1

- name: splunk install
  yum: name=/tmp/{{splunk_rpm}} state=present
  when: is_splunk_installed.rc == 1

- name: splunk init.d check
  command: ls /etc/init.d/splunk
  register: is_splunk_enabled
  failed_when: is_splunk_enabled.rc not in [0,2]
  changed_when: is_splunk_enabled.rc != 0

- name: splunk enable
  command: /opt/splunk/bin/splunk enable boot-start --accept-license
  when: is_splunk_enabled.rc != 0

- name: splunk service enabled
  service: name=splunk state=started enabled=yes
